version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: oz_a2m_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-mqtt-datasource
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/var/lib/grafana/dashboards
      - grafana-storage:/var/lib/grafana
    networks:
      - oz_a2m_network
    restart: unless-stopped

volumes:
  grafana-storage:

networks:
  oz_a2m_network:
    driver: bridge
